config/routes.rb
Rails.application.routes.draw do
  # 管理画面
  devise_for :admin_users, path: :admin, controllers: {
    sessions: 'admin/admin_users/sessions',
    passwords: 'admin/admin_users/passwords',
  }
  namespace :admin do
    resources :admin_users do
      collection do
        get :password
        patch :password_update
      end
    end
  end

  # 送信メール (development only)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name,
    presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/admin_users/passwords_controller.rb
class Admin::AdminUsers::PasswordsController < Devise::PasswordsController

  layout 'admin_nologin'

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
    admin_admin_users_path
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || admin_admin_users_path
  end
end

app/controllers/admin/admin_users/sessions_controller.rb
class Admin::AdminUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  layout 'admin_nologin'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || admin_admin_users_path
  end

  def after_sign_out_path_for(resource)
    new_admin_user_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < Admin::BaseController
  before_action :set_admin_user, only: %i(show edit update destroy)

  def index
    @q = AdminUser.ransack(params[:q])
    @q.sorts = 'id asc' if @q.sorts.empty?
    @admin_users = @q.result.page(params[:page])
  end

  def show
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
      redirect_to admin_admin_user_path(@admin_user),
      notice: t('admin.messages.create.success')
    else
      flash.now[:alert] = t('admin.messages.create.failure')
      render :new
    end
  end

  def edit
  end

  def update
    if @admin_user.update(admin_user_params)
      redirect_to admin_admin_user_path(@admin_user),
        notice: t('admin.messages.update.success')
    else
      flash.now[:alert] = t('admin.messages.update.failure')
      render :edit
    end
  end

  def destroy
    @admin_user.destroy!
    redirect_to admin_admin_users_path,
      notice: t('admin.messages.destroy.success')
  end

  def password
  end

  def password_update
    if current_admin_user.update(admin_user_params)
      bypass_sign_in(current_admin_user)
      redirect_to admin_admin_user_path(current_admin_user),
        notice: t('admin.messages.update.success')
    else
      flash.now[:alert] = t('admin.messages.update.failure')
      render :password
    end
  end

  private

  def set_admin_user
    @admin_user = AdminUser.find(params[:id])
  end

  def admin_user_params
    params.require(:admin_user).permit(
      :id,
      :name,
      :email,
      :password,
      :password_confirmation,
    )
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # https://github.com/charliesome/better_errors/issues/341
  before_action :better_errors_hack, if: -> { Rails.env.development? }

  private

  def better_errors_hack
    request.env['puma.config'].options.user_options.delete :app
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admin_users/_form.html.slim
= bootstrap_form_for [:admin, resource] do |f|
  = f.text_field :name
  = f.text_field :email
  - if resource.new_record?
    = f.password_field :password
    = f.password_field :password_confirmation
  = f.submit

app/views/admin/admin_users/edit.html.slim
- content_for :title, t('admin.actions.edit')
- breadcrumb :admin, @admin_user
.x_panel
  .x_content
    = render 'form', resource: @admin_user

app/views/admin/admin_users/index.html.slim
- content_for :title, t('admin.title.admin_users.index')
- breadcrumb :admin_users
.x_panel
  .x_content
    .pull-right
      ul.list-inline
        li = link_to t('admin.actions.new'), new_admin_admin_user_path, class: 'btn-new'
    .clearfix
    table.table.table-hover
      thead
        tr
          th = sort_link @q, :id
          th = sort_link @q, :name
          th = sort_link @q, :email
          th = sort_link @q, :created_at
          th = sort_link @q, :updated_at
          th
      tbody
        - @admin_users.each do |admin_user|
          tr
            td = admin_user.id
            td = admin_user.name
            td = admin_user.email
            td = l(admin_user.created_at)
            td = l(admin_user.updated_at)
            td = link_to t('admin.actions.show'), admin_admin_user_path(admin_user), class: 'btn-show'
    = paginate @admin_users, theme: :admin

app/views/admin/admin_users/new.html.slim
- content_for :title, t('admin.actions.new')

.x_panel
  .x_content
    = render 'form', resource: @admin_user

app/views/admin/admin_users/password.html.slim
- content_for :title, t('admin.header.password')

.x_panel
  .x_content
    = bootstrap_form_for [:admin, current_admin_user], url: password_update_admin_admin_users_path do |f|
      = f.password_field :password
      = f.password_field :password_confirmation
      = f.submit

app/views/admin/admin_users/show.html.slim
- content_for :title, @admin_user.name
- breadcrumb :admin_user, @admin_user
.x_panel
  .x_content
    .pull-right
      ul.list-inline
        li = link_to t('admin.actions.edit'), edit_admin_admin_user_path(@admin_user), class: 'btn-edit'
        li = link_to t('admin.actions.destroy'), admin_admin_user_path(@admin_user), class: 'btn-destroy', method: :delete, data: { confirm: t('admin.messages.destroy.confirm') }
    .clearfix
    dl.dl-horizontal
      dt = AdminUser.human_attribute_name(:id)
      dd = @admin_user.id
      dt = AdminUser.human_attribute_name(:name)
      dd = @admin_user.name
      dt = AdminUser.human_attribute_name(:email)
      dd = @admin_user.email
      dt = AdminUser.human_attribute_name(:created_at)
      dd = l(@admin_user.created_at)
      dt = AdminUser.human_attribute_name(:updated_at)
      dd = l(@admin_user.updated_at)

app/views/layouts/admin.html.slim
doctype html
html lang="ja"
  head
    meta charset="utf8"
    title = t('admin.site_title')
    = csrf_meta_tags

    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    = stylesheet_link_tag 'https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css'
    = stylesheet_link_tag 'admin', media: 'all'

  body.nav-md
    .container.body
      .main_container
        .col-md-3.left_col
          .left_col.scroll-view
            .navbar.nav_title
              = link_to '#', class: 'site_title' do
                = t('admin.site_title')
            .clearfix
            #sidebar-menu.main_menu_side.hidden-print.main_menu
              .menu_section
                ul.nav.side-menu
                  li
                    = link_to admin_admin_users_path do
                      i.fa.fa-user
                      = t('admin.title.admin_users.index')

        .top_nav
          .nav_menu
            nav
              .nav.toggle
                a#menu_toggle
                  i.fa.fa-bars
              ul.nav.navbar-nav.navbar-right
                li
                  a.user-profile.dropdown-toggle data-toggle="dropdown"
                    i.fa.fa-user-secret
                    | &nbsp;
                    = current_admin_user.name
                    | &nbsp;
                    i.fa.fa-angle-down
                  ul.dropdown-menu.dropdown-usermenu.pull-right
                    li = link_to t('admin.header.edit'), edit_admin_admin_user_path(current_admin_user)
                    li = link_to t('admin.header.password'), password_admin_admin_users_path
                    li.divider
                    li = link_to t('admin.header.sign_out'), destroy_admin_user_session_path, method: :delete

        .right_col role="main"
          .page-title
            .title_left
              h3 = yield :title
            .title_right
              == breadcrumbs style: :bootstrap
          .clearfix
          - if notice
            .flash-notice = notice
          - if alert
            .flash-alert = alert
          = yield

    = javascript_include_tag 'admin'

app/views/layouts/admin_nologin.html.slim
doctype html
html lang="ja"
  head
    meta charset="utf8"
    title = t('admin.site_title')
    = csrf_meta_tags

    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    = stylesheet_link_tag 'admin', media: 'all'

  body.login
    .login_wrapper
      .animate.form.login_form
        section.login_content
          - if notice
            .flash-notice = notice
          - if alert
            .flash-alert = alert
          = yield

app/views/layouts/admin_user_mailer.text.erb
<%= yield %>

--------------------------------------------------------------
【お問い合わせ】
こちらのメールアドレスは送信専用です。
ご返信いただいてもお答えできませんのでご了承ください。

ご質問・お問い合わせの際は、大変お手数ですが下記メールアドレスまでご連絡をお願いいたします。
xxxx@xxxx

[会社名]
http://ーーーーーーーーーーーー